CREATE TABLE PEDIDOS (
items integer,
cajas_grandes integer,
cajas_pequenas integer,
cantidad_cajas integer
);

CREATE OR REPLACE FUNCTION CALCULAR_CAJAS_NECESARIAS (ITEMS IN INTEGER) 
RETURN NUMBER
AS
CAJAS_NECESARIAS INTEGER :=0;
CAJAS_GRANDES INTEGER;
CAJAS_PEQUENAS INTEGER:=0;
DIVISION decimal(15,2);
DISION_ENTERA INTEGER;
resul decimal(15,6) :=0;
BEGIN
DISION_ENTERA := ITEMS/5;
DIVISION := ITEMS/5;
resul := DIVISION - DISION_ENTERA;
if resul <> 0 then 
 CAJAS_PEQUENAS:=1;
end if;
IF ITEMS > 1  THEN 
  CAJAS_GRANDES := ITEMS/5;
END IF;
CAJAS_NECESARIAS:= CAJAS_GRANDES + CAJAS_PEQUENAS;
RETURN CAJAS_NECESARIAS;
END CALCULAR_CAJAS_NECESARIAS;


CREATE OR REPLACE FUNCTION VERIFICAR_PEDIDO (ITEMS IN INTEGER,CAJAS_GRADES IN INTEGER,CAJAS_PEQUENAS IN INTEGER) 
RETURN NUMBER
AS
TOTAL_CAJAS INTEGER;
BEGIN
TOTAL_CAJAS := CAJAS_GRADES+ CAJAS_PEQUENAS;
IF TOTAL_CAJAS < CALCULAR_CAJAS_NECESARIAS(ITEMS) OR (CAJAS_GRADES = 1 AND ITEMS < 5) THEN 
RETURN -1;
ELSE 
RETURN CAJAS_GRADES+CAJAS;
END IF;
END VERIFICAR_PEDIDO;  


CREATE OR REPLACE PROCEDURE PROCESAR_PEDIDOS () 

RETURN NUMBER

AS

BEGIN

END CALCULAR_CAJAS_NECESARIAS;  

